import os
import subprocess
import webbrowser


def main() -> None:
    command = [
        "pytest",
        "-W",
        "ignore::DeprecationWarning",
        "--cov-report",
        "html",
        "--cov=yotse",
        "tests/",
    ]
    try:
        # Set a timeout for the tests in case some qcg process doesn't terminate
        subprocess.run(command, check=True, timeout=300)
    except subprocess.TimeoutExpired:
        print("The tests did not complete within the timeout period.")
    except subprocess.CalledProcessError as e:
        print(f"Tests failed with error: {e}")


def open_coverage_report() -> None:
    dir_path = "htmlcov"  # This is the default directory name for HTML reports generated by coverage
    index_file_path = os.path.join(dir_path, "index.html")
    absolute_path = os.path.abspath(index_file_path)
    webbrowser.open(f"file://{absolute_path}")


if __name__ == "__main__":
    main()
