import os
import subprocess
import webbrowser


def main():
    command = [
        "pytest",
        "-W",
        "ignore::DeprecationWarning",
        "--cov-report",
        "html",
        "--cov=yotse",
        "tests/",
    ]
    subprocess.run(command, check=True)


def open_coverage_report():
    dir_path = "htmlcov"  # This is the default directory name for HTML reports generated by coverage
    index_file_path = os.path.join(dir_path, "index.html")
    absolute_path = os.path.abspath(index_file_path)
    webbrowser.open(f"file://{absolute_path}")


if __name__ == "__main__":
    main()
