"""Module to provide poetry with functions to run all tests."""

import os
import subprocess
import webbrowser


def main() -> None:
    """Run the test suite with coverage and generate an HTML report.

    This function executes the test suite using pytest with coverage enabled.
    It suppresses DeprecationWarnings, generates an HTML coverage report in the 'htmlcov' directory,
    and opens the coverage report in the default web browser.

    Raises
    ------
    subprocess.CalledProcessError
        If the test suite fails.
    """
    command = [
        "pytest",
        "-W",
        "ignore::DeprecationWarning",
        "--cov-report",
        "html",
        "--cov=yotse",
        "tests/",
    ]
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        print(f"Tests failed with error: {e}")


def open_coverage_report() -> None:
    """Open the HTML coverage report in the default web browser.

    This function opens the HTML coverage report generated by the test suite in the
    default web browser.
    """
    dir_path = "htmlcov"  # This is the default directory name for HTML reports generated by coverage
    index_file_path = os.path.join(dir_path, "index.html")
    absolute_path = os.path.abspath(index_file_path)
    webbrowser.open(f"file://{absolute_path}")


if __name__ == "__main__":
    main()
