name: Build and Deploy Documentation

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '1.7.0'

    - name: Install dependencies
      run: poetry install

    - name: Build Sphinx Documentation
      run: |
        poetry run sphinx-build -b html docs/source docs/build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
